name: Build LaTeX documents
on: [push]
jobs:
  build_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: |
            cd documents/slides
            ./make_handout
          work_in_root_file_dir: true
          root_file: |
            documents/short-abstract/short-abstract.tex
            documents/summary/summary.tex
            documents/thesis/thesis.tex
            documents/slides/slides.tex
            documents/slides/slides-handout.tex

      - name: Move compiled files
        run: |
          mkdir outputs/
          mv documents/short-abstract/
          mv documents/summary/
          mv documents/thesis/
          mv documents/slides/

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-documents
          path: outputs/

  # send_to_server:
  #   needs: build_latex
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: compiled-documents
  #         path: .
  #     - name: Install SSH & tools
  #       run: |
  #         sudo apt-get install -y sshpass
  #         sudo apt-get install -y ssh
  #     - name: Upload artifacts
  #       env:
  #         SSHUSER: ${{ secrets.SSHUSER }}
  #         SSHSERVER: ${{ secrets.SSHSERVER }}
  #         SSHPATH: ${{ secrets.SSHPATH }}
  #         SSHPASS: ${{ secrets.SSHPASS }}
  #       run: |
  #         sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no appunti.pdf $SSHUSER@$SSHSERVER:$SSHPATH
  #         sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no presentazione-handout.pdf $SSHUSER@$SSHSERVER:$SSHPATH
  #         sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no presentazione.pdf $SSHUSER@$SSHSERVER:$SSHPATH
  #         sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no long-abstract.pdf $SSHUSER@$SSHSERVER:$SSHPATH