name: Build LaTeX documents
on: [push]
jobs:
  compile_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Generate printable thesis
        run: |
          cd documents/thesis
          ./make_printable

      - name: Generate handout for slides
        run: |
          cd documents/slides
          ./make_handout

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: |
            documents/short-abstract/short-abstract.tex
            documents/summary/summary.tex
            documents/thesis/thesis.tex
            documents/thesis/thesis-printable.tex
            documents/slides/slides.tex
            documents/slides/slides-handout.tex

      - name: Move compiled files
        run: |
          mkdir outputs/
          mv documents/short-abstract/*.pdf outputs/
          mv documents/summary/*.pdf outputs/
          mv documents/thesis/*.pdf outputs/
          mv documents/thesis/thesis-printable.tex outputs/
          mv documents/slides/*.pdf outputs/

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-documents
          path: outputs/

  send_to_server:
    needs: compile_documents
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: compiled-documents
          path: .
      - name: Install SSH & tools
        run: |
          sudo apt-get install -y sshpass
          sudo apt-get install -y ssh
      - name: Upload artifacts
        env:
          SSHUSER: ${{ secrets.SSHUSER }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
          SSHPATH: ${{ secrets.SSHPATH }}
          SSHPASS: ${{ secrets.SSHPASS }}
        run: |
          sshpass -e scp -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no *.pdf $SSHUSER@$SSHSERVER:$SSHPATH